# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navipermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='navi_user_groups_permissions', to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='navipermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='navi_user_permissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
