# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='项目名')),
                ('dever', models.URLField(verbose_name='负责人')),
                ('apps', models.TextField(blank=True, default='', verbose_name='组件')),
                ('rely', models.TextField(blank=True, default='', verbose_name='依赖')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('groups', models.ManyToManyField(blank=True, related_name='projects_groups', to='users.UserGroup', verbose_name='User group')),
                ('users', models.ManyToManyField(blank=True, related_name='projects_users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
