# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
                ('category', models.CharField(default='default', max_length=128)),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
