# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('logo', models.ImageField(default='image/default.png', upload_to='pictures/')),
                ('url', models.URLField(verbose_name='网址')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
            ],
        ),
    ]
